<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="DESKTOP-0QFFCOH" failures="2" tests="3" name="Test" time="5.031" errors="0" timestamp="2022-10-22T17:07:28 EDT">
  <testcase classname="com.test.tests.AutomationScripts" name="TC01AllEmployeedata" time="3.017"/>
  <testcase classname="com.test.tests.AutomationScripts" name="TC02CreateEmployee" time="0.427">
    <failure type="com.fasterxml.jackson.databind.exc.UnrecognizedPropertyException" message="Unrecognized field &amp;quot;status&amp;quot; (class com.test.models.CreateEmp1POJO), not marked as ignorable (5 known properties: &amp;quot;employee_salary&amp;quot;, &amp;quot;employee_name&amp;quot;, &amp;quot;profile_image&amp;quot;, &amp;quot;employee_age&amp;quot;, &amp;quot;id&amp;quot;])
 at [Source: (String)&amp;quot;{&amp;quot;status&amp;quot;:&amp;quot;success&amp;quot;,&amp;quot;data&amp;quot;:{&amp;quot;employee_name&amp;quot;:&amp;quot;test&amp;quot;,&amp;quot;employee_salary&amp;quot;:&amp;quot;123&amp;quot;,&amp;quot;employee_age&amp;quot;:&amp;quot;23&amp;quot;,&amp;quot;profile_image&amp;quot;:&amp;quot;\&amp;quot; \&amp;quot;&amp;quot;,&amp;quot;id&amp;quot;:8445},&amp;quot;message&amp;quot;:&amp;quot;Successfully! Record has been added.&amp;quot;}&amp;quot;; line: 1, column: 12] (through reference chain: com.test.models.CreateEmp1POJO[&amp;quot;status&amp;quot;])">
      <![CDATA[com.fasterxml.jackson.databind.exc.UnrecognizedPropertyException: Unrecognized field "status" (class com.test.models.CreateEmp1POJO), not marked as ignorable (5 known properties: "employee_salary", "employee_name", "profile_image", "employee_age", "id"])
 at [Source: (String)"{"status":"success","data":{"employee_name":"test","employee_salary":"123","employee_age":"23","profile_image":"\" \"","id":8445},"message":"Successfully! Record has been added."}"; line: 1, column: 12] (through reference chain: com.test.models.CreateEmp1POJO["status"])
at com.fasterxml.jackson.databind.exc.UnrecognizedPropertyException.from(UnrecognizedPropertyException.java:61)
at com.fasterxml.jackson.databind.DeserializationContext.handleUnknownProperty(DeserializationContext.java:1127)
at com.fasterxml.jackson.databind.deser.std.StdDeserializer.handleUnknownProperty(StdDeserializer.java:2023)
at com.fasterxml.jackson.databind.deser.BeanDeserializerBase.handleUnknownProperty(BeanDeserializerBase.java:1700)
at com.fasterxml.jackson.databind.deser.BeanDeserializerBase.handleUnknownVanilla(BeanDeserializerBase.java:1678)
at com.fasterxml.jackson.databind.deser.BeanDeserializer.vanillaDeserialize(BeanDeserializer.java:320)
at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserialize(BeanDeserializer.java:177)
at com.fasterxml.jackson.databind.deser.DefaultDeserializationContext.readRootValue(DefaultDeserializationContext.java:323)
at com.fasterxml.jackson.databind.ObjectMapper._readMapAndClose(ObjectMapper.java:4674)
at com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:3629)
at com.fasterxml.jackson.databind.ObjectMapper$readValue$0.call(Unknown Source)
at io.restassured.internal.path.json.mapping.JsonPathJackson2ObjectDeserializer.deserialize(JsonPathJackson2ObjectDeserializer.groovy:46)
at io.restassured.path.json.mapping.JsonPathObjectDeserializer$deserialize.call(Unknown Source)
at io.restassured.internal.mapping.Jackson2Mapper.deserialize(Jackson2Mapper.groovy:58)
at io.restassured.mapper.ObjectMapper$deserialize.call(Unknown Source)
at io.restassured.internal.mapping.ObjectMapping.parseWithJackson2(ObjectMapping.groovy:254)
at io.restassured.internal.mapping.ObjectMapping$parseWithJackson2$0.callStatic(Unknown Source)
at io.restassured.internal.mapping.ObjectMapping.deserialize(ObjectMapping.groovy:56)
at io.restassured.internal.mapping.ObjectMapping$deserialize.call(Unknown Source)
at io.restassured.internal.RestAssuredResponseOptionsGroovyImpl.as(RestAssuredResponseOptionsGroovyImpl.groovy:231)
at io.restassured.internal.RestAssuredResponseOptionsImpl.as(RestAssuredResponseOptionsImpl.java:169)
at simpleCRUD.CreateEmployee.AddEmployee(CreateEmployee.java:15)
at com.test.tests.AutomationScripts.TC02CreateEmployee(AutomationScripts.java:23)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 27 stack frames]]>
    </failure>
  </testcase> <!-- TC02CreateEmployee -->
  <testcase classname="com.test.tests.AutomationScripts" name="TC05GetEmpWithId" time="0.515">
    <failure type="java.lang.AssertionError" message="1 expectation failed.
JSON path data.employee_salary doesn&amp;apos;t match.
Expected: 170750
  Actual: &amp;lt;170750&amp;gt;
">
      <![CDATA[java.lang.AssertionError: 1 expectation failed.
JSON path data.employee_salary doesn't match.
Expected: 170750
  Actual: <170750>

at org.codehaus.groovy.runtime.callsite.ConstructorSite$ConstructorSiteNoUnwrapNoCoerce.callConstructor(ConstructorSite.java:105)
at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCallConstructor(CallSiteArray.java:59)
at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callConstructor(AbstractCallSite.java:263)
at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callConstructor(AbstractCallSite.java:277)
at io.restassured.internal.ResponseSpecificationImpl$HamcrestAssertionClosure.validate(ResponseSpecificationImpl.groovy:499)
at io.restassured.internal.ResponseSpecificationImpl$HamcrestAssertionClosure$validate$1.call(Unknown Source)
at io.restassured.internal.ResponseSpecificationImpl.validateResponseIfRequired(ResponseSpecificationImpl.groovy:684)
at org.codehaus.groovy.runtime.callsite.PlainObjectMetaMethodSite.doInvoke(PlainObjectMetaMethodSite.java:43)
at org.codehaus.groovy.runtime.callsite.PogoMetaMethodSite$PogoCachedMethodSiteNoUnwrapNoCoerce.invoke(PogoMetaMethodSite.java:193)
at org.codehaus.groovy.runtime.callsite.PogoMetaMethodSite.callCurrent(PogoMetaMethodSite.java:61)
at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callCurrent(AbstractCallSite.java:185)
at io.restassured.internal.ResponseSpecificationImpl.body(ResponseSpecificationImpl.groovy:262)
at io.restassured.specification.ResponseSpecification$body$1.callCurrent(Unknown Source)
at io.restassured.internal.ResponseSpecificationImpl.body(ResponseSpecificationImpl.groovy:109)
at io.restassured.internal.ValidatableResponseOptionsImpl.body(ValidatableResponseOptionsImpl.java:244)
at io.restassured.internal.ValidatableResponseImpl.super$2$body(ValidatableResponseImpl.groovy)
at groovy.lang.MetaMethod.doMethodInvoke(MetaMethod.java:323)
at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1268)
at org.codehaus.groovy.runtime.ScriptBytecodeAdapter.invokeMethodOnSuperN(ScriptBytecodeAdapter.java:144)
at io.restassured.internal.ValidatableResponseImpl.body(ValidatableResponseImpl.groovy:298)
at io.restassured.internal.ValidatableResponseImpl.body(ValidatableResponseImpl.groovy)
at com.test.helpers.ReusableMethods.validate_equal(ReusableMethods.java:35)
at simpleCRUD.GetEmployee.getempwithid(GetEmployee.java:15)
at com.test.tests.AutomationScripts.TC05GetEmpWithId(AutomationScripts.java:29)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 42 stack frames]]>
    </failure>
  </testcase> <!-- TC05GetEmpWithId -->
</testsuite> <!-- Test -->
